# === Prompt de dos líneas ===
format = """
[](#89b4fa)\
$username\
[](bg:#fab387 fg:#89b4fa)\
$time\
[](bg:#f9e2af fg:#fab387)\
$custom\
[](#f9e2af)

[](#89dceb)\
$directory\
[](fg:#89dceb bg:#cba6f7)\
$git_branch\
$git_status\
[](fg:#cba6f7 bg:#1e1e2e)\
$character
"""

# === Usuario ===
[username]
show_always = true
style_user = "bg:#89b4fa fg:#1e1e2e bold"
format = "[  $user ]($style_user)"

# === Hora ===
[time]
disabled = false
time_format = "%H:%M:%S"
style = "bg:#fab387 fg:#1e1e2e bold"
format = "[  $time ]($style)"

# === Arch (como módulo personalizado) ===
[custom.arch]
command = "echo  CachyOS"
style = "bg:#f9e2af fg:#1e1e2e bold"
format = "[ $output ]($style)"
when = true

# === Carpeta actual ===
[directory]
style = "bg:#89dceb fg:#1e1e2e bold"
format = "[  $path ]($style)"

# === Git ===
[git_branch]
symbol = ""
style = "bg:#cba6f7 fg:#1e1e2e bold"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:#cba6f7 fg:#1e1e2e"
format = '[ $all_status ]($style)'

# === Símbolo de prompt ===
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
